image: 'alpine/git'

variables:
  GIT_SUBMODULE_STRATEGY: recursive

stages:
  - deploy

deploy:
  stage: deploy
  script:
#    - git clone --recursive "$CI_REPOSITORY_URL" wmapp-UnofficialWestmontApp
#    - cd wmapp-UnofficialWestmontApp
    - git config user.email "kg6zvp@gmail.com"
    - git config --global user.name "Sam McCollum"
    - git remote add github "https://kg6zvp:$GITHUB_PERSONAL_ACCESS_TOKEN@github.com/kg6zvp/wmapp-UnofficialWestmontApp.git"
    - git push --force --follow-tags github master
#    - cd ..
#    - rm -rf wmapp-UnofficialWestmontApp
  only:
    - master

after_script:
  - echo "End CI"
